# Generated by Django 4.1.5 on 2023-01-25 10:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='credit_score',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='customer_age',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='quotes',
            name='license_length',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='martial_status',
            field=models.CharField(choices=[('S', 'single'), ('M', 'married'), ('D', 'divorced')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='net_price',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='profit',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='sale_indicator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotes',
            name='tax',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='test_group',
            field=models.CharField(choices=[('A', 'test group A'), ('B', 'test group B')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='quotes',
            name='total_price',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='quotes',
            name='vehicle_mileage',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='vehicle_value',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
