# Generated by Django 4.1.5 on 2023-01-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_quotes_credit_score_quotes_customer_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='license_length',
            new_name='licence_length',
        ),
        migrations.RenameField(
            model_name='quotes',
            old_name='martial_status',
            new_name='marital_status',
        ),
    ]
