# Generated by Django 4.1.5 on 2023-01-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_license_length_quotes_licence_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='credit_score',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
    ]
