# Generated by Django 4.1.5 on 2023-01-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_quotes_credit_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='licence_length',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='net_price',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='profit',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='tax',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='total_price',
            field=models.DecimalField(decimal_places=8, max_digits=12, null=True),
        ),
    ]
